// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCw8OJoW7aW_s8boQzv_Xmg9JgJizRJok',
    appId: '1:672895120333:web:28ba35b1382e89b5510a84',
    messagingSenderId: '672895120333',
    projectId: 'mahfazty-c7651',
    authDomain: 'mahfazty-c7651.firebaseapp.com',
    storageBucket: 'mahfazty-c7651.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBENzhoancXe29av80oxo7xiT-_gHzudh0',
    appId: '1:672895120333:android:b377104ee8304e9a510a84',
    messagingSenderId: '672895120333',
    projectId: 'mahfazty-c7651',
    storageBucket: 'mahfazty-c7651.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADeR_dgBbK-qrIaOnOGOwhEe035yjr_Qc',
    appId: '1:672895120333:ios:20ea27c73e6ccfe1510a84',
    messagingSenderId: '672895120333',
    projectId: 'mahfazty-c7651',
    storageBucket: 'mahfazty-c7651.appspot.com',
    iosBundleId: 'com.example.mahfazty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADeR_dgBbK-qrIaOnOGOwhEe035yjr_Qc',
    appId: '1:672895120333:ios:20ea27c73e6ccfe1510a84',
    messagingSenderId: '672895120333',
    projectId: 'mahfazty-c7651',
    storageBucket: 'mahfazty-c7651.appspot.com',
    iosBundleId: 'com.example.mahfazty',
  );
}
